### ISSUE TITLE
Study 클래스의 @NoArgsConstructor 어노테이션 확인 요망

### ISSUE THREAD

**Issue by Deocksoo** [lv4-project/Woowahan-Tech-Co-learning#11]
![image](https://user-images.githubusercontent.com/38533611/69834009-0c9b4080-127b-11ea-84fd-4c9c5e77653f.png)

빌드가 제대로 되지 않는데, 아직 문제를 파악하지 못했습니다. 확인 필요합니다.

**Comment by ep1stas1s** [comment]
lombok의 어노테이션 중 `@NoArgsConstructor`의 옵션이 `access = AccessLevel.PRIVATE`으로 되어있어서 그런 것 같습니다.
PRIVATE으로 유지하려면 아래 같은 방법으로 생성 가능합니다.
```
Study study = Study.builder().build();
```
그게 아니라면 lombok 재설정이 필요할 거 같습니다...

**Comment by Deocksoo** [comment]
아하.. 한번 변경해볼게요!
