### ISSUE TITLE
사용하지 않는 import 발견

### ISSUE THREAD

**Issue by ddu0422** [lv4-project/Woowahan-Tech-Co-learning#13]
![image](https://user-images.githubusercontent.com/43198414/69841400-4c295300-12a2-11ea-98a8-3ed1d7fa82b6.png)

사용하지 않는 import는 제거하는게 좋지 않을까요?

**Comment by Deocksoo** [comment]
앗 ... 급하게 작성하다보니... ㅎㅎ 수정하겠습니다
