### ISSUE TITLE
추가되는 코딩 컨벤션 제안

### ISSUE THREAD

**Issue by Deocksoo** [lv4-project/Woowahan-Tech-Co-learning#16]
- RestController에 Rest 안 붙이고 시작한다.
- 모든 api 콜은 /api path를 붙인다
- 모든 javascript 문자열은 ``로 감싼다.

**Comment by ddu0422** [comment]
예를 들면, UserApiController라고 붙이나요?

**Comment by Deocksoo** [comment]
지금 저희가 만들게 될 Controller들이 모두 RestController들이니 아예 api나 rest라는 수식어를 다 빼자는 의견이 있었어요. 그런데 조금 생각해보니 유지보수 측면에서는 붙여놓는게 나을 수도 있을것 같네요. 음... 이 부분 월요일에 다시 이야기해보는거 어떨까요?
