### ISSUE TITLE
스터디 모집 인원 

### ISSUE THREAD

**Issue by ddu0422** [lv4-project/Woowahan-Tech-Co-learning#19]
- 웹 페이지에서 인원 수를 dropbox로 할까요 아니면 number로 직접 입력받을까요?

**Comment by Deocksoo** [comment]
number로 입력하는게 어떨까요? 어차피 back에서 검토하는 로직이 필요하니, 프론트쪽에서만 검사 한번 더 해주면 dropbox보다는 직접 입력이 사용성 측면에서 나을것 같아서요!
