### ISSUE TITLE
Jenkins 자동 배포 문서화

### ISSUE THREAD

**Issue by Deocksoo** [lv4-project/Woowahan-Tech-Co-learning#2]
- 자동 배포시 필요한 배경 지식 문서화
- 시나리오 작성

**Comment by Deocksoo** [comment]
배포 시나리오가 완성되면 한번 공유하는 시간 갖도록 하겠습니다

**Comment by ep1stas1s** [comment]
https://github.com/lv4-project/Woowahan-Tech-Co-learning/wiki/Docker-&-Jenkins-&-PM2
