### ISSUE TITLE
홈페이지를 리다이렉트 한다.

### ISSUE THREAD

**Issue by woowahanCU** [lv4-project/Woowahan-Tech-Co-learning#238]
https://tecolearning.com/

홈페이지에 아무 정보도 나오지 않는 것은 사용자 경험에 좋지 않다.

모집 중 페이지로 리다이렉트 하는 것은 어떨까
> https://tecolearning.com/recruitment

**Comment by Deocksoo** [comment]
피드백 반영 완료!
