### ISSUE TITLE
프로필 정보의 사용자 이름을 변경한다.

### ISSUE THREAD

**Issue by woowahanCU** [lv4-project/Woowahan-Tech-Co-learning#239]
사용자 이름이 깃헙의 username 혹은 변경을 유도하는 이름 '닉네임을 변경하세요' 로 설정하는 것은 어떨까

moomin은 잘못된 정보라고 인식된다고 생각합니다.

<img width="366" alt="스크린샷 2020-04-21 오전 11 54 05" src="https://user-images.githubusercontent.com/46308585/79820674-c1b7cc00-83c7-11ea-8d64-b3d0f7e995e5.png">

**Comment by Deocksoo** [comment]
피드백 반영하였습니다
