### ISSUE TITLE
검색 조건을 명시한다.

### ISSUE THREAD

**Issue by woowahanCU** [lv4-project/Woowahan-Tech-Co-learning#242]
모임을 검색하는 조건이 타이틀인지 컨텐츠인지 작성자인지 확인이 불가하다.
타이틀로 보이는데 임시적으로 명시하는 것이 직관적이라고 생각한다.
추가 검색 조건 기능은 별도의 이슈를 할당하고 추가하는 것은 어떨까

**Comment by Deocksoo** [comment]
이슈 확인 후 반영하였습니다~
