### ISSUE TITLE
검색 페이지의 기준과 모집 페이지의 기준을 맞춘다.

### ISSUE THREAD

**Issue by woowahanCU** [lv4-project/Woowahan-Tech-Co-learning#243]
<img width="691" alt="스크린샷 2020-04-21 오후 12 09 40" src="https://user-images.githubusercontent.com/46308585/79821173-0859f600-83c9-11ea-9578-a26c61183c9d.png">

영문과 한글을 혼용할 필요가 있을까

**Comment by Deocksoo** [comment]
혼용하지 않도록 수정하였습니다!
