### ISSUE TITLE
유저 정보 가져오는 api 결정 문제

### ISSUE THREAD

**Issue by yunheehyeon** [lv4-project/Woowahan-Tech-Co-learning#30]
유저 프로필 페이지를 위해 로그인 한 유저의 정보를 서버에서 가져와야 합니다.

1. 프론트(Vue)쪽에서 로그인 한 유저의 id(primary key) 를 전역 변수처럼 관리하고, 이를 사용해서 서버에 특정 id 의 유저 정보를 요청하는 방법.
  - e.g., /api/users/{id}

2. 서버에 직접 로그인 한 유저 정보를 요청하는 방법.
  - e.g., /api/users/loggedin

1번 방법은 프론트에서 관리해줘야한다는 귀찮은 점이 있지만, api 명세가 깔끔해짐.

2번 방법은 프론트에서 id 관리를 해줄 필요가 없지만, api 가 더러워짐. (게다가, 어차피 1번 같은 api 는 필요함. 나중에 다른 사용자의 프로필을 볼 일이 있기 때문)

**Comment by yunheehyeon** [comment]
게다가 1번 방법은 어떻게서든 간에 유저가 로그인 한 id 를 자바스크립트 코드로 변경할 수도 있지 않을까?

근데 이게 문제가 될까?

**Comment by green4469** [comment]
1번 방식으로 구현하기로 했습니다~
