### ISSUE TITLE
유저 삭제 Hard delete vs Soft delete

### ISSUE THREAD

**Issue by yunheehyeon** [lv4-project/Woowahan-Tech-Co-learning#32]
유저에 딸린 정보들이 많을텐데 (유저가 지난 스터디들에서 모아논 산출물 등)

유저를 삭제하면 정보들이 전부 삭제되면 안되니까

Soft delete 로 구현할까요?

아니면 일단 급한대로

Hard delete 로 구현할까요?

아니면 delete 나중에 구현한다고 생각하고 pr 보낼까요?

CRU 까지 구현했습니다.

**Comment by ddu0422** [comment]
- soft delete
  - 이유: 안해봐서

**Comment by green4469** [comment]
Soft delete 로 하겠습니다. 이슈 닫을게요~
