### ISSUE TITLE
자바스크립트 구버전 사용에 의한 XSS 잠재 보안 위협

### ISSUE THREAD

**Issue by green4469** [lv4-project/Woowahan-Tech-Co-learning#59]
[보안 이슈](https://github.com/lv4-project/Woowahan-Tech-Co-learning/network/alert/src/frontend/package-lock.json/serialize-javascript/open)

**Comment by Deocksoo** [comment]
serialized-javascript를 npm 으로 설치해야 합니다.

https://www.npmjs.com/package/serialize-javascript
