### ISSUE TITLE
Entity 생성자 validation 시 DTO -> Entity 변환에 제약

### ISSUE THREAD

**Issue by green4469** [lv4-project/Woowahan-Tech-Co-learning#67]
# 문제 상황

Entity 에서 데이터베이스에 저장될 때는 Entity의 필드에 @Pattern 애너테이션을 붙여서 JPA 로 필드의 정합성을 검증

``` java
// TODO

``` 

Entity 의 값들이 데이터베이스에 들어갈 때 뿐만아니라 Entity 의 생성자에서 인자 값들을 검증해 올바른 Entity 만 돌아다니도록 만들고자 했음.

여기서 문제가 발생함.

DTO 에서 toEntity 메서드를 통해 Entity 로 만드는데, 이 과정에서 DTO 에 누락된 필드 값은 null 로 채워짐. null 값들 때문에 생성자의 인자 검증에서 예외가 발생. 즉, 필드가 하나라도 누락된 DTO 는 toEntity 호출시 예외가 발생한다.

-> 일단 생성자에서 인자를 검증하지 않도록 수정하여 문제를 해결.

어떻게 해야할까?

**Comment by ddu0422** [comment]
validation 을 없앤다
