### ISSUE TITLE
interceptor로 인해 static 파일을 가져오지 못하는 문제

### ISSUE THREAD

**Issue by ddu0422** [lv4-project/Woowahan-Tech-Co-learning#98]
- pwa 적용 시 static file이 자동으로 index.html과 같은 root에 생겨 interceptor를 계속 수정해야하는 문제 발생

**Comment by Deocksoo** [comment]
엇 ㄷㄷ 어떤 상황인지 잘 모르겠어요. static file 경로가 어떻게 잡히나요? 기능이 추가될 때마다 계속 새로운 파일들이 추가되어서 그런건가요?

**Comment by Deocksoo** [comment]
혹시 vue.config.js 파일에서 outputDir 수정하는걸로는 해결이 안되나요?
